//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads_PageName
    {
        public int AdsPageId { get; set; }
        public Nullable<int> AdsPlacementId { get; set; }
        public string PageName { get; set; }
        public string Status { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
