//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributes_Setup
    {
        public int AttributeId { get; set; }
        public string AttributeName { get; set; }
        public string AttributeDescription { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
