//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int BrandId { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string BrandName { get; set; }
        public string BrandDescription { get; set; }
        public string BrandImage { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string UserName { get; set; }
        public string BrandURLPath { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
