//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_master
    {
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string URLPath { get; set; }
        public Nullable<int> parent_category_id { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string Banner { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> IsShowHomePage { get; set; }
        public Nullable<bool> IsIncludeMenu { get; set; }
        public string SEO_PageName { get; set; }
        public string SEO_Title { get; set; }
        public string SEO_Keyword { get; set; }
        public string SEO_Description { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
