//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Three
    {
        public int CategoryThreeId { get; set; }
        public Nullable<int> CategoryTwoId { get; set; }
        public string CategoryThreeName { get; set; }
        public string UrlPath { get; set; }
        public string Icon { get; set; }
        public string Banner { get; set; }
        public string Description { get; set; }
        public string IsFeatured { get; set; }
        public string Status { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
