//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Master
    {
        public int RequestFundId { get; set; }
        public Nullable<System.Guid> RequestFundGUID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<bool> AdminStatus { get; set; }
        public string AdminRemarks { get; set; }
        public string PaypalID { get; set; }
        public Nullable<decimal> Administrativefee { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
