//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Received
    {
        public int DonationReceivedId { get; set; }
        public Nullable<System.Guid> RequestFundGUID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaypalId { get; set; }
        public Nullable<decimal> AdministrativeFeesPer { get; set; }
        public Nullable<decimal> AdministrativeAmount { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
