//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Setup
    {
        public int EmailSettingId { get; set; }
        public string EmailFrom { get; set; }
        public string Password { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public string Host { get; set; }
        public string BCC { get; set; }
        public string Type { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
