//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logo
    {
        public int LogoId { get; set; }
        public string Logo1 { get; set; }
        public Nullable<int> logowidth { get; set; }
        public Nullable<int> logoheight { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string SupportContact { get; set; }
        public string WebsiteName { get; set; }
        public string FooterLogo { get; set; }
        public string Favicon { get; set; }
        public string Title { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
