//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MesageId { get; set; }
        public Nullable<System.Guid> ChatID { get; set; }
        public string sender { get; set; }
        public string recipient { get; set; }
        public Nullable<System.DateTime> senddate { get; set; }
        public Nullable<System.DateTime> recieveddate { get; set; }
        public string status { get; set; }
        public string Message1 { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> SessionBookingId { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
