//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status
    {
        public int OrderStatusId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string Remarks { get; set; }
        public string Insertby { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
