//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int OrderDetailId { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public Nullable<decimal> DeliveryFees { get; set; }
        public Nullable<decimal> TotalOrderAmount { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
