//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Basic
    {
        public int OrderId { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> DeliveryFees { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string Comments { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Donation { get; set; }
        public string OrderVariation { get; set; }
        public string LastOrderStatus { get; set; }
        public Nullable<int> currencyid { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
