//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageCategory
    {
        public int PageCategoryId { get; set; }
        public Nullable<int> MainPageCategoryId { get; set; }
        public string Type { get; set; }
        public string PageCategory1 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<bool> IsURL { get; set; }
        public string URL { get; set; }
        public Nullable<int> Sortnumber { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
