//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_SEO
    {
        public int SEOId { get; set; }
        public Nullable<System.Guid> ProductGUID { get; set; }
        public string SEO_PageName { get; set; }
        public string SEO_MetaTItle { get; set; }
        public string SEO_Keywords { get; set; }
        public string SEO_Metadescription { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
