//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Discount
    {
        public int DiscountId { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> DiscountOffer { get; set; }
        public Nullable<System.DateTime> DiscountStartDate { get; set; }
        public Nullable<System.DateTime> DiscountEndDate { get; set; }
        public string ModuleType { get; set; }
        public string ModuleID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
