//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Price
    {
        public int ProductPriceId { get; set; }
        public Nullable<System.Guid> ProductGUID { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<bool> DisableBuyButton { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public Nullable<decimal> DeliveryFees { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
