//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Basic
    {
        public int ProductId { get; set; }
        public Nullable<System.Guid> ProductGUID { get; set; }
        public string ProductName { get; set; }
        public string URLPath { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string SKU { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<System.DateTime> ProductStartDate { get; set; }
        public Nullable<System.DateTime> ProductEndDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string CoverImage { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
