//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public Nullable<int> Star { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string Module { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
