//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int SocialMediaId { get; set; }
        public string Icon { get; set; }
        public string URL { get; set; }
        public string Status { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
