//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusId { get; set; }
        public string Status1 { get; set; }
        public string URLPath { get; set; }
        public Nullable<bool> ShowOnFront { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string UserName { get; set; }
        public string CssClass { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
