//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Profile
    {
        public int ProfileId { get; set; }
        public System.Guid ProfileGUID { get; set; }
        public string UserName { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string AdminStatus { get; set; }
        public string Status { get; set; }
        public string ShopName { get; set; }
        public string Logo { get; set; }
        public string ContactNumber { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string ShopDescription { get; set; }
        public string PaypalId { get; set; }
        public string CoverImage { get; set; }
        public string ShopURLPath { get; set; }
        public Nullable<bool> IsMembershipFree { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
