//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Membership
    {
        public int MembershipId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> MembershipFee { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public string ReferenceId { get; set; }
        public string MembershipStatus { get; set; }
        public string CancelStatus { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> Cancellationdate { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
