//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Membership_Package
    {
        public int Membershipid { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Membershiptype { get; set; }
        public Nullable<int> RecurringPeriod { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Sortoption { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
