//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Setup
    {
        public int WebsiteSetupId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string UserName { get; set; }
        public string ItemKey { get; set; }
        public string Type { get; set; }
        public string DeductionType { get; set; }
        public Nullable<int> OrgId { get; set; }
    }
}
